name: Benchmark Kieker-java
on:
  workflow_dispatch:
  push:
    branches: [ main, continuous-gh-benchmarks ]
  schedule: 
    - cron: "0 3 * * *"


permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Performance measurement
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '3.5.3'
      - uses: actions/setup-go@v4
        with:
          go-version: "stable"
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Execute MooBench Benchmark
        run: |
          ./setup.sh
          cd frameworks/Kieker-java/
          export NUM_OF_LOOPS=2 
          export MOOBENCH_CONFIGURATIONS="0 4"
          export SLEEP_TIME=0
          export TOTAL_NUM_OF_CALLS=10000
          ./benchmark.sh 
          cd results-Kieker-java
          unzip results.zip 
          ../../../analysis/getGHActionsFormat.sh &> output.json
          cat output.json
          mv output.json ../../../
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: 'Kieker-java'
          tool: 'customSmallerIsBetter'
          output-file-path: output.json
          fail-on-alert: true
          auto-push: false
      - name: Start ssh-agent and add private key
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY_MOOBENCH_DATA }}          
      - name: Add github.com to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
      - name: Push benchmark result
        env:
          TARGET_SSH: git@github.com:kieker/moobench-data.git
          TARGET_BRANCH: gh-pages
        run: git push "$TARGET_SSH" "$TARGET_BRANCH"
